apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config-${CONFIG_MAP_POSTFIX}
  labels:
    app: postgres-${CONFIG_MAP_POSTFIX}
data:
  POSTGRES_DB: ${SERVICE_DB_NAME}
  POSTGRES_USER: ${USERNAME}
  POSTGRES_PASSWORD: ${PASSWORD}
  POSTGRES_HOST: ${HOST}
  DATASOURCE: dbname=${SERVICE_DB_NAME} host=${HOST} user=${USERNAME} password=${PASSWORD} sslmode=disable
  DB_CREATE_SQL: |
    CREATE DATABASE ${SERVICE_DB_NAME};
    CREATE USER ${USERNAME} WITH ENCRYPTED PASSWORD '${PASSWORD}';
    GRANT ALL PRIVILEGES ON DATABASE ${SERVICE_DB_NAME} TO ${USERNAME};